permalink: /:year/:title/

gems: [jekyll-paginate]

# Setup
title:               pixelbar
tagline:             "Hackerspace in Rotterdam, The Netherlands"
description:         "Hackerspace in Rotterdam, The Netherlands"
url:                 'http://pixelbar.github.io'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Pixelbar
  url:               https://twitter.com/pixelbar010
  email:             bestuur@pixelbar.nl

# Custom vars
version:             1.0.0
